// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../../mocks/stats/mock_service.go -package=statsmocks
//

// Package statsmocks is a generated GoMock package.
package statsmocks

import (
	reflect "reflect"

	stats "github.com/fatmalabidi/buzzfizz/internal/services/stats"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetMostFrequent mocks base method.
func (m *MockService) GetMostFrequent() (*stats.RequestStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMostFrequent")
	ret0, _ := ret[0].(*stats.RequestStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMostFrequent indicates an expected call of GetMostFrequent.
func (mr *MockServiceMockRecorder) GetMostFrequent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMostFrequent", reflect.TypeOf((*MockService)(nil).GetMostFrequent))
}

// Record mocks base method.
func (m *MockService) Record(int1, int2, limit int, str1, str2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", int1, int2, limit, str1, str2)
}

// Record indicates an expected call of Record.
func (mr *MockServiceMockRecorder) Record(int1, int2, limit, str1, str2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockService)(nil).Record), int1, int2, limit, str1, str2)
}
