// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetSequencesFizzbuzzParams defines parameters for GetSequencesFizzbuzz.
type GetSequencesFizzbuzzParams struct {
	// Int1 first divisor
	Int1 int `form:"int1" json:"int1"`

	// Str1 String that will replace all numbers divisible by int1.
	Str1 string `form:"str1" json:"str1"`

	// Int2 second divisor
	Int2 int `form:"int2" json:"int2"`

	// Str2 String that will replace all numbers divisible by int2.
	Str2 string `form:"str2" json:"str2"`

	// Limit Array size.
	Limit int `form:"limit" json:"limit"`
}
