// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../../mocks/fizzbuzz/mock_service.go -package=fizzbuzzmocks
//

// Package fizzbuzzmocks is a generated GoMock package.
package fizzbuzzmocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockService) Generate(int1, int2, limit int, str1, str2 string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", int1, int2, limit, str1, str2)
	ret0, _ := ret[0].([]string)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockServiceMockRecorder) Generate(int1, int2, limit, str1, str2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockService)(nil).Generate), int1, int2, limit, str1, str2)
}
